name: React CI

on:
  push:
    branches:
      -'master'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      -uses: actions/checkout@v1
      -run: npm install
      -run: mpm run build
      -run: npm test